Name: qqbot
Mode: dev

Pulsar:
  Url: "pulsar://localhost:6650"
  Main: "persistent://echo-wing/main"
  Dlq: "persistent://echo-wing/dlq/all"

Consul:
  Host: "localhost"
  Port: 8500
  Base: "echo_wing/"
  Token: ""
  Scheme: "http"

NatCat:
  Http: "http://localhost:3001"
  Token: "Qq360123."
  TimeOut: 10 # s
